name: CI
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the lint script
        run: |
          npm ci ,
          lint ,
          npm audit fix ,
          echo "Linting..."
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the lint script
        run: |
          npm ci ,
          test , 
          echo "Testing..."
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the lint script
        run: |
          npm ci ,
          build ,
          echo "Building..."
