name: CI
on:
  push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint 
          echo "Linting...Done"

      - name: Test
        run: |
          npm run test  
          echo "Testing...Done"

      - name: Build
        run: |
          npm run build 
          echo "Building...Done"
